Update spikeinterface to fix preprocessing error
I encountered the error posted below.

Updating spikeinterface to 0.13.0 (and updating its related packages)
fixed this. I'm not sure which package update fixed the error and do not
want to investigate this due to dependency hell...

```
Loading continuous data...
Loading continuous data...
No sorting range specified. I will sort the whole recording
Traceback (most recent call last):
  File
"/data/in_vivo_ephys_openephys-master/.snakemake/scripts/tmp4hlldf77.01_sorting.py",
line 63, in <module>
    recording = st.preprocessing.remove_bad_channels(recording,
bad_channel_ids=bad_channel) #remove bad channel
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/remove_bad_channels.py",
line 77, in remove_bad_channels
    bad_threshold=bad_threshold, seconds=seconds, verbose=verbose)
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/remove_bad_channels.py",
line 16, in __init__
    BasePreprocessorRecordingExtractor.__init__(self,
self._subrecording)
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/basepreprocessorrecording.py",
line 16, in __init__
    self.copy_times(recording)
AttributeError: 'RemoveBadChannelsRecording' object has no attribute
'copy_times'
[Fri Oct  1 16:04:35 2021]
Error in rule sort_spikes:
    jobid: 8
    output:
/data/M1_D21_2019-12-18_15-11-22_VR/processed/mountainsort4/sorter.pkl,
/data/M1_D21_2019-12-18_15-11-22_VR/processed/mountainsort4/sorter_df.pkl,
/data/M1_D21_2019-12-18_15-11-22_VR/processed/recording_info.pkl

RuleException:
CalledProcessError in line 18 of
/data/in_vivo_ephys_openephys-master/workflow/workflow_common.smk:
Command 'set -euo pipefail;  /opt/conda/envs/ms4/bin/python
/data/in_vivo_ephys_openephys-master/.snakemake/scripts/tmp4hlldf77.01_sorting.py'
returned non-zero exit status 1.
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 2189, in run_wrapper
  File
"/data/in_vivo_ephys_openephys-master/workflow/workflow_common.smk",
line 18, in __rule_sort_spikes
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 529, in _callback
  File "/opt/conda/envs/ms4/lib/python3.6/concurrent/futures/thread.py",
line 56, in run
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 515, in cached_or_run
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 2201, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log:
/data/in_vivo_ephys_openephys-master/.snakemake/log/2021-10-01T160428.891048.snakemake.log
Loading continuous data...
Loading continuous data...
No sorting range specified. I will sort the whole recording
Traceback (most recent call last):
  File
"/data/in_vivo_ephys_openephys-master/.snakemake/scripts/tmp4hlldf77.01_sorting.py",
line 63, in <module>
    recording = st.preprocessing.remove_bad_channels(recording,
bad_channel_ids=bad_channel) #remove bad channel
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/remove_bad_channels.py",
line 77, in remove_bad_channels
    bad_threshold=bad_threshold, seconds=seconds, verbose=verbose)
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/remove_bad_channels.py",
line 16, in __init__
    BasePreprocessorRecordingExtractor.__init__(self,
self._subrecording)
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/spiketoolkit/preprocessing/basepreprocessorrecording.py",
line 16, in __init__
    self.copy_times(recording)
AttributeError: 'RemoveBadChannelsRecording' object has no attribute
'copy_times'
[Fri Oct  1 16:04:35 2021]
Error in rule sort_spikes:
    jobid: 8
    output:
/data/M1_D21_2019-12-18_15-11-22_VR/processed/mountainsort4/sorter.pkl,
/data/M1_D21_2019-12-18_15-11-22_VR/processed/mountainsort4/sorter_df.pkl,
/data/M1_D21_2019-12-18_15-11-22_VR/processed/recording_info.pkl

RuleException:
CalledProcessError in line 18 of
/data/in_vivo_ephys_openephys-master/workflow/workflow_common.smk:
Command 'set -euo pipefail;  /opt/conda/envs/ms4/bin/python
/data/in_vivo_ephys_openephys-master/.snakemake/scripts/tmp4hlldf77.01_sorting.py'
returned non-zero exit status 1.
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 2189, in run_wrapper
  File
"/data/in_vivo_ephys_openephys-master/workflow/workflow_common.smk",
line 18, in __rule_sort_spikes
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 529, in _callback
  File "/opt/conda/envs/ms4/lib/python3.6/concurrent/futures/thread.py",
line 56, in run
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 515, in cached_or_run
  File
"/opt/conda/envs/ms4/lib/python3.6/site-packages/snakemake/executors/__init__.py",
line 2201, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log:
/data/in_vivo_ephys_openephys-master/.snakemake/log/2021-10-01T160428.891048.snakemake.log
```